apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-back-restic-cache-claim
  namespace: consul-back
spec:
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce